
version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./docker/postgres-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=social_restaurant
  social-restaurant-booking-api:
    build:
      context: .
    image: nelotest/social-restaurant-booking-api
    hostname: social-restaurant-booking-api
    environment:
      - NELO_TEST_DATABASE_URL=jdbc:postgresql://postgres:5432/social_restaurant?user=postgres&password=postgres
    ports:
      - "8080:8080"
    init: true
    depends_on:
      - postgres
