server:
  port: 8080
spring:
  datasource:
    url: ${NELO_TEST_DATABASE_URL_FOR_TESTS}:#{"NOT_PRESENT"}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql=true
logging:
  level:
    org:
      hibernate:
        type: trace
flyway:
  enabled: true
